//! Explicit policies for peripherals that are not behaviourally modelled.
//!
//! FID-15 keeps these out of the "accidental RAM byte" bucket.  If DLCP
//! firmware touches one of these SFRs, the simulator gives it deterministic
//! register storage and documented no-side-effect behavior instead of silently
//! implying that CCP waveforms, comparator analog thresholds, HLVD trips, FVR
//! settling, or PSP/SPP transfers are implemented.

use crate::memory::{Address, Memory, Variant};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum StubBehavior {
    /// Register is present and readable/writable through the listed mask, but
    /// no waveform, analog, voltage-trip, or interrupt side effects are
    /// generated by this stub.
    RegisterBackedNoSideEffects { writable_mask: u8 },
    /// The DLCP package/variant does not expose this peripheral; no SFR is
    /// owned by the simulator for it.
    NotPresentOnDlcpPackage,
}

#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub struct StubPolicy {
    pub variant: Variant,
    pub peripheral: &'static str,
    pub sfr: &'static str,
    pub addr: Option<u16>,
    pub behavior: StubBehavior,
    pub citation: &'static str,
    pub dlcp_scope: &'static str,
}

const K20_POLICIES: &[StubPolicy] = &[
    StubPolicy {
        variant: Variant::Pic18F25K20,
        peripheral: "HLVD",
        sfr: "HLVDCON",
        addr: Some(0xFD2),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0xBF },
        citation: "DS40001303H Reg 22-1 / Table 4-4: HLVDCON bit 6 unimplemented",
        dlcp_scope: "DLCP control firmware does not use voltage-trip events; PIR2.HLVDIF is never synthesized",
    },
    StubPolicy {
        variant: Variant::Pic18F25K20,
        peripheral: "CCP/ECCP/PWM",
        sfr: "CCP1CON",
        addr: Some(0xFBD),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0xFF },
        citation: "DS40001303H §15/§16 CCP/ECCP/PWM registers",
        dlcp_scope: "No DLCP control path uses capture/compare/PWM outputs",
    },
    StubPolicy {
        variant: Variant::Pic18F25K20,
        peripheral: "CCP/ECCP/PWM",
        sfr: "CCP2CON",
        addr: Some(0xFBA),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0x3F },
        citation: "DS40001303H Register map: CCP2CON reset --00_0000",
        dlcp_scope: "No CCP2 capture/compare/PWM timing or flags are generated",
    },
    StubPolicy {
        variant: Variant::Pic18F25K20,
        peripheral: "CCP/ECCP/PWM",
        sfr: "PWM1CON/PSTRCON/ECCP1AS",
        addr: Some(0xFB7),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0xFF },
        citation: "DS40001303H §16 ECCP PWM side registers",
        dlcp_scope: "PWM steering/autoshutdown side effects are out of DLCP scope",
    },
    StubPolicy {
        variant: Variant::Pic18F25K20,
        peripheral: "Comparator/CVREF/FVR",
        sfr: "CM1CON0/CM2CON0/CM2CON1",
        addr: Some(0xF7B),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0xFF },
        citation: "DS40001303H §20 comparator control registers",
        dlcp_scope: "Comparator outputs and C1/C2 interrupt flags are not synthesized",
    },
    StubPolicy {
        variant: Variant::Pic18F25K20,
        peripheral: "Comparator/CVREF/FVR",
        sfr: "CVRCON",
        addr: Some(0xFB5),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0xFF },
        citation: "DS40001303H §21 comparator voltage reference",
        dlcp_scope: "CVREF analog output is not routed into GPIO/ADC/comparators",
    },
    StubPolicy {
        variant: Variant::Pic18F25K20,
        peripheral: "Comparator/CVREF/FVR",
        sfr: "CVRCON2",
        addr: Some(0xFB4),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0x80 },
        citation: "DS40001303H CVRCON2 reset 00--_----; FVRST is status-only",
        dlcp_scope: "FVR enable is stored, but FVR settling/analog consumers are not modelled",
    },
    StubPolicy {
        variant: Variant::Pic18F25K20,
        peripheral: "PSP/SPP",
        sfr: "PSP/SPP register block",
        addr: None,
        behavior: StubBehavior::NotPresentOnDlcpPackage,
        citation: "DS40001303H pin tables: PSP is a 40/44-pin feature",
        dlcp_scope: "DLCP CONTROL is the 28-pin PIC18F25K20 package",
    },
];

const PIC2455_POLICIES: &[StubPolicy] = &[
    StubPolicy {
        variant: Variant::Pic18F2455,
        peripheral: "HLVD",
        sfr: "HLVDCON",
        addr: Some(0xFD2),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0xBF },
        citation: "DS39632E Reg 22-1 / Table 4-4: HLVDCON bit 6 unimplemented",
        dlcp_scope: "DLCP MAIN does not consume HLVD trips; PIR2.HLVDIF is never synthesized",
    },
    StubPolicy {
        variant: Variant::Pic18F2455,
        peripheral: "CCP/ECCP/PWM",
        sfr: "CCP1CON",
        addr: Some(0xFBD),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0x3F },
        citation: "DS39632E Register 16-1: 28-pin CCP1CON upper mode bits unavailable",
        dlcp_scope: "No CCP1 capture/compare/PWM output is generated",
    },
    StubPolicy {
        variant: Variant::Pic18F2455,
        peripheral: "CCP/ECCP/PWM",
        sfr: "CCP2CON",
        addr: Some(0xFBA),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0x3F },
        citation: "DS39632E §15 CCP2 control, upper reset bits unimplemented",
        dlcp_scope: "No CCP2 timing or interrupt flag is generated",
    },
    StubPolicy {
        variant: Variant::Pic18F2455,
        peripheral: "CCP/ECCP/PWM",
        sfr: "ECCP1DEL/ECCP1AS",
        addr: Some(0xFB6),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0x80 },
        citation: "DS39632E §16 notes enhanced PWM outputs are disabled on 28-pin devices",
        dlcp_scope: "Enhanced PWM dead-band/autoshutdown is out of DLCP MAIN scope",
    },
    StubPolicy {
        variant: Variant::Pic18F2455,
        peripheral: "Comparator/CVREF/FVR",
        sfr: "CMCON",
        addr: Some(0xFB4),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0xFF },
        citation: "DS39632E Register 22-1 comparator control",
        dlcp_scope: "Comparator outputs and CMIF are not synthesized",
    },
    StubPolicy {
        variant: Variant::Pic18F2455,
        peripheral: "Comparator/CVREF/FVR",
        sfr: "CVRCON",
        addr: Some(0xFB5),
        behavior: StubBehavior::RegisterBackedNoSideEffects { writable_mask: 0xFF },
        citation: "DS39632E §23 comparator voltage reference",
        dlcp_scope: "CVREF is register-visible only; no analog routing side effects",
    },
    StubPolicy {
        variant: Variant::Pic18F2455,
        peripheral: "PSP/SPP",
        sfr: "SPPCON/SPPCFG/SPPEPS/SPPDATA",
        addr: None,
        behavior: StubBehavior::NotPresentOnDlcpPackage,
        citation: "DS39632E §18 and NC/ICPORTS note: 28-pin configuration disables SPP",
        dlcp_scope: "DLCP MAIN uses the 28-pin PIC18F2455 package; SPP SFRs are not modelled",
    },
    StubPolicy {
        variant: Variant::Pic18F2455,
        peripheral: "Comparator/CVREF/FVR",
        sfr: "FVRCON",
        addr: None,
        behavior: StubBehavior::NotPresentOnDlcpPackage,
        citation: "DS39632E exposes CVREF/band-gap but no K20-style FVRCON SFR",
        dlcp_scope: "No separate 2455 FVR SFR is represented",
    },
];

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct PeripheralStubs {
    variant: Variant,
}

impl PeripheralStubs {
    pub fn new(variant: Variant) -> Self {
        PeripheralStubs { variant }
    }

    pub fn reset_state(&mut self) {}

    pub fn on_sfr_write(&mut self, addr: u16, _value: u8, mem: &mut Memory) {
        for policy in policies_for(self.variant) {
            if policy.addr != Some(addr) {
                continue;
            }
            match policy.behavior {
                StubBehavior::RegisterBackedNoSideEffects { writable_mask } => {
                    let value = mem.read_raw(Address::from_raw(addr)) & writable_mask;
                    mem.write_raw(Address::from_raw(addr), value);
                }
                StubBehavior::NotPresentOnDlcpPackage => {
                    mem.write_raw(Address::from_raw(addr), 0x00);
                }
            }
        }
    }
}

pub fn policies_for(variant: Variant) -> &'static [StubPolicy] {
    match variant {
        Variant::Pic18F25K20 => K20_POLICIES,
        Variant::Pic18F2455 => PIC2455_POLICIES,
    }
}
